#  spring.datasource.url = jdbc:mysql://192.168.1.225:3306/sam
#    spring.datasource.username = sam
#    spring.datasource.password = 123qweASD
server:
  port: 8088
spring:
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        mysql:
          url: jdbc:mysql://192.168.1.225:3306/sam
          username: sam
          password: 123qweASD
          driver-class-name: com.mysql.cj.jdbc.Driver
#        sqlserver:
#          url: jdbc:sqlserver://192.168.1.225:1433;database=sam;encrypt=true;trustServerCertificate=true
#          username: sam
#          password: Password666
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  mapper-locations: classpath:mapperxml/*.xml


